version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbmovie
      MYSQL_USER: movie
      MYSQL_PASSWORD: password
    volumes: 
      - vmariadbmovie:/var/lib/mysql
        # - ./db_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80

  api:
    build:
      context: .
      args:
        repodir: ${repodir}
        artifact: ${artifact}
        confname: ${confname}
    ports:
      - 8080:8080
    
volumes:
  vmariadbmovie:

