version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: dbmovie
      MARIADB_USER: movie
      MARIADB_PASSWORD: password
    volumes: 
      - vmariadbmovie:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80

  api:
    build:
      context: .
      args:
        repodir: ${repodir}
        artifact: ${artifact}
        confname: ${confname}
    ports:
      - 8080:8080
    
volumes:
  vmariadbmovie:

